### ISSUE TITLE
Cannot load model

### ISSUE THREAD

**Issue by parthe** [castorini/docTTTTTquery#13]
The code for loading the model checkpoint: 
`model = T5ForConditionalGeneration.from_pretrained('model.ckpt-1004000', from_tf=True, config=config)`
gives an error: 
` File "C:\Users\pparthe\AppData\Roaming\Python\Python36\site-packages\transformers\modeling_utils.py", line 633, in from_pretrained
    if resolved_archive_file.endswith(".index"):

AttributeError: 'NoneType' object has no attribute 'endswith'`

**Comment by rodrigonogueira4** [comment]
Could you please confirm that the files below are in your current directory?

`model.ckpt-1004000.data-00000-of-00002`
`model.ckpt-1004000.data-00001-of-00002`
`model.ckpt-1004000.index`
`model.ckpt-1004000.meta`

**Comment by rodrigonogueira4** [comment]
Closing this as there is not activity.
