### ISSUE TITLE
Cannot Predict Queries from Passages by Tensorflow

### ISSUE THREAD

**Issue by k-yudong** [castorini/docTTTTTquery#15]
Hi, I have trouble predicting queries from passages by Tensorflow. 
After following the instructions in README, these `predicted_queries_topk_sample.txt.*` files I finally got contain **a large number of empty lines** and **a few lines that contain only one word(`what`, `which`, `define`, etc).**

**Comment by rodrigonogueira4** [comment]
It looks like the model checkpoint was not loaded correctly. Could you please check if `--model_dir` contains `model.ckpt-1004000*` files?

**Comment by k-yudong** [comment]
Thanks for your reply. I don't know what happened, but it works normally now.
