### ISSUE TITLE
'Tensor' object has no attribute 'bool'

### ISSUE THREAD

**Issue by tengteng-Lin** [castorini/docTTTTTquery#16]
`(pytorch) D:\workplace\doc2query>python test.py
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    num_return_sequences=3)
  File "D:\application\Anaconda3\envs\pytorch\lib\site-packages\torch\autograd\grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "D:\application\Anaconda3\envs\pytorch\lib\site-packages\transformers\modeling_utils.py", line 1181, in generate
    model_specific_kwargs=model_specific_kwargs,
  File "D:\application\Anaconda3\envs\pytorch\lib\site-packages\transformers\modeling_utils.py", line 1279, in _generate_no_beam_search
    is_sents_unfinished_and_token_to_add_is_eos = unfinished_sents.mul(eos_in_sents.long()).bool()
AttributeError: 'Tensor' object has no attribute 'bool'`

When I run the code to test,I meet this error.Maybe it is because Tensorflow version is wrong? My tensorflow-gpu is 1.12.0.
Hope you give me some help.

**Comment by tengteng-Lin** [comment]
I hava installed tensorflow-gpu==2.0.0 and torch==1.1.0，but don’t solve it.
Hope your reply!

**Comment by rodrigonogueira4** [comment]
It seems that you are using pytorch, not Tensorflow.

Can you tell me which pytorch and HF-transformers versions you are using?

Also, could you please copy and paste the script here?

**Comment by tengteng-Lin** [comment]
> It seems that you are using pytorch, not Tensorflow.
> 
> Can you tell me which pytorch and HF-transformers versions you are using?
> 
> Also, could you please copy and paste the script here?

I hava solved it,it is because pytorch version is [wrong,](https://github.com/bentrevett/pytorch-seq2seq/issues/58) can solve it.

Thanks for reply!

**Comment by rodrigonogueira4** [comment]
I'm glad it worked!
