### ISSUE TITLE
Document collection predicted queries

### ISSUE THREAD

**Issue by Fatima-200159617** [castorini/docTTTTTquery#18]
Hi,
Thanks for sharing the predicted queries for documents. I was trying to download them but I am not able to do so as I am getting the following error which seems a common error when downloading form google storage using gsutils.
**Caught socket error, retrying: [Errno 101] Network is unreachable**. 
Please advice. Is it possible to share it through dropbox as you did for passages. 
Many thanks in advance.

**Comment by rodrigonogueira4** [comment]
For that link, you need to use `wget`, not `gsutil`:
```
$ wget https://storage.googleapis.com/doctttttquery_git/predicted_queries_topk_sampling.zip

--2020-07-24 06:36:30--  https://storage.googleapis.com/doctttttquery_git/predicted_queries_topk_sampling.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.10.16, 142.250.64.80, 172.217.165.144, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.10.16|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7932436541 (7.4G) [application/zip]
Saving to: ‘predicted_queries_topk_sampling.zip’

100%[===========================================================================================================================>] 7,932,436,541  104MB/s   in 86s    

2020-07-24 06:37:57 (88.0 MB/s) - ‘predicted_queries_topk_sampling.zip’ saved [7932436541/7932436541]

```

If you want to use gsutil, you need to replace `https://storage.googleapis.com/` with `gs://`, like this:
`gsutil cp gs://doctttttquery_git/predicted_queries_topk_sampling.zip .`

**Comment by Fatima-200159617** [comment]
Thanks a lot, so basically it is the same folder I downloaded for passages predicted queries right?
I want to expand the documents collection using the below command. How can I get **segment_doc_ids.txt ** file using wget command
python convert_msmarco_doc_to_anserini.py \
  --original_docs_path=./msmarco-docs.tsv.gz \
  --doc_ids_path=./segment_doc_ids.txt \
  --predictions_path=./predicted_queries_topk.txt-1004000 \
  --output_docs_path=./expanded_docs/docs.json

**Comment by rodrigonogueira4** [comment]
`wget https://storage.googleapis.com/neuralresearcher_data/doc2query_t5_msmarco_doc/data/1/segment_doc_ids.txt`

**Comment by Fatima-200159617** [comment]
Thanks Rodrigo, 
I am getting this error when trying to download it using your shared command
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.194.128, 2404:6800:4003:c04:                             :80, 2404:6800:4003:c03::80, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.194.128|:443... connected.
Unable to establish SSL connection.

**Comment by rodrigonogueira4** [comment]
It works fine for me: 

```
$ wget https://storage.googleapis.com/neuralresearcher_data/doc2query_t5_msmarco_doc/data/1/segment_doc_ids.txt

--2020-07-26 15:17:14--  https://storage.googleapis.com/neuralresearcher_data/doc2query_t5_msmarco_doc/data/1/segment_doc_ids.txt
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.11.48, 142.250.64.112, 172.217.6.240, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.11.48|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 178283761 (170M) [text/plain]
Saving to: ‘segment_doc_ids.txt’

100%[=============================================================================================================================>] 178,283,761  227MB/s   in 0.7s   

2020-07-26 15:17:15 (227 MB/s) - ‘segment_doc_ids.txt’ saved [178283761/178283761]
```

**Comment by rodrigonogueira4** [comment]
Were you able to download from the link? Are you behind any company or government firewall?

**Comment by Fatima-200159617** [comment]
Solved thanks Rodrigo.
