### ISSUE TITLE
Any text processing have used when training the T5 model?

### ISSUE THREAD

**Issue by ArvinZhuang** [castorini/docTTTTTquery#19]
Hi,
I'm curious about that did you use the raw document and query text as training data? or you did some text processing before feeding them into the model (for example, text to lower case for documents).

Thank you!

**Comment by rodrigonogueira4** [comment]
We simply used triples.train.small.tsv from MS MARCO without any preprocessing.

**Comment by ArvinZhuang** [comment]
Thank you for your reply!

I didn't realize that it was the small training set used to train the model. Was there any reason that you didn't use the full training set? and did you use triplet losses to train? or only took the positive examples from the triples.train.small?

I'm asking these details because I want to finetune a GPT2 to do the same job. 

Cheers~

**Comment by rodrigonogueira4** [comment]
I'm sorry, I was got confused with the other repository. 
docTTTTTquery was trained using the qrels.train.tsv, queries.train.tsv and collection.tsv files from here:
https://msmarco.blob.core.windows.net/msmarcoranking/collectionandqueries.tar.gz
which are exactly the same files used to train the original doc2query from this repo: https://github.com/nyu-dl/dl4ir-doc2query

**Comment by ArvinZhuang** [comment]
That’s make sense, thank your for the clarification.

**Comment by ArvinZhuang** [comment]
Btw, do you think it could have some gains to use GPT to do docTquery instead of T5?

**Comment by rodrigonogueira4** [comment]
We tried it with GPT-2 but it was worse than T5. We will publish the results in one or two months. I think Pegasus or BART are more promising, but we haven't tried with them.

**Comment by ArvinZhuang** [comment]
I see, thank you!
