### ISSUE TITLE
Error while predicting in TensorFlow

### ISSUE THREAD

**Issue by genderbias** [castorini/docTTTTTquery#22]
Hi,
I could not train the model to use it. I could predict using PyTorch. However, When I try to use TensorFlow in order to predict queries, I get the following error again : 
`  File "/home/ngr_arabzadeh/.local/lib/python3.7/site-packages/mesh_tensorflow/simd_mesh_impl.py", line 864, in auto_logical_to_physical_tpu
    "physical_shape=%s logical_shape=%s" % (physical_shape, logical_shape))
ValueError: physical and logical shapes must have the same product physical_shape=[2, 2, 2] logical_shape=[128]
  In call to configurable 'decode' (<function decode at 0x7f8e374ce400>)
  In call to configurable 'decode_from_file' (<function decode_from_file at 0x7f8e374cea60>)
  In call to configurable 'infer_model' (<function infer_model at 0x7f8e374d5488>)
  In call to configurable 'run' (<function run at 0x7f8e374da048>)`

**Comment by rodrigonogueira4** [comment]
Does adding `--gin_param="utils.tpu_mesh_shape.tpu_topology ='v3-8'" ` as proposed in https://github.com/castorini/docTTTTTquery/issues/21 solve your problem?

**Comment by lintool** [comment]
Seeing no follow-up, closing.
