### ISSUE TITLE
Off by one bug in document expansion?

### ISSUE THREAD

**Issue by lintool** [castorini/docTTTTTquery#36]
The MS MARCO document corpus should have 3,213,835 documents, but after doc expansion, we only have 3,213,834 documents.

I suspect there's an off-by-one error somewhere...

**Comment by richard3983** [comment]
The last document is missing after the doc expansion. In `convert_msmarco_doc_to_anserini.py`, the last expanded doc won't get a chance to be written into the output file because there is no more new doc_id_ref after it. It can be fixed by adding another writing operation at the end of the script.

**Comment by lintool** [comment]
As I suspected. Can you please fix?

**Comment by richard3983** [comment]
Yes, I just sent a PR for that.

**Comment by lintool** [comment]
Addressed by https://github.com/castorini/docTTTTTquery/pull/38

**Comment by lintool** [comment]
Wrapping up this thread, I have rerun both doc expansion, per-doc and per-passage:

```
$ wc msmarco-doc-expanded/docs.json
 3213835 5019568105 31029552685 msmarco-doc-expanded/docs.json

$ wc old/msmarco-doc-expanded/docs.json
 3213834 5019566465 31029542791 old/msmarco-doc-expanded/docs.json

$ tail msmarco-doc-expanded/docs.json | cut -f1 -d','
{"id": "D1685530"
{"id": "D3112790"
{"id": "D779825"
{"id": "D2803363"
{"id": "D2735170"
{"id": "D2027345"
{"id": "D3094124"
{"id": "D1659457"
{"id": "D1633167"
{"id": "D1551606"

$ tail old/msmarco-doc-expanded/docs.json | cut -f1 -d','
{"id": "D3056582"
{"id": "D1685530"
{"id": "D3112790"
{"id": "D779825"
{"id": "D2803363"
{"id": "D2735170"
{"id": "D2027345"
{"id": "D3094124"
{"id": "D1659457"
{"id": "D1633167"
```

No surprise, MRR did not change.

Also, no changes to per-passage doc expansion.

We can consider this issue closed now.
