### ISSUE TITLE
How do I predict more than one query on TPU?

### ISSUE THREAD

**Issue by Narabzad** [castorini/docTTTTTquery#44]
Hello,

I am able to predict one query per document with T5 Inference with TensorFlow on Google TPU but how do I predict more than one query per document?

**Comment by lintool** [comment]
hey @Narabzad for faster service, you can find us on Slack! Do you have an account? If not, email me and we'll get you set up...

**Comment by Narabzad** [comment]
Yes! What workspace I should join?

**Comment by lintool** [comment]
Send me email.
