### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by jobergum** [castorini/docTTTTTquery#55]
I see this repo misses license, would you consider open sourcing this as Apache 2.0 as with https://github.com/castorini?

**Comment by rodrigonogueira4** [comment]
Sure: https://github.com/castorini/docTTTTTquery/pull/56

**Comment by jobergum** [comment]
Thanks a lot!

**Comment by lintool** [comment]
We'll see this integrated into the next Vespa release? ;)

**Comment by jobergum** [comment]
:) it’s a great model and we used it for our document ranking run on ms
marco. Making the license change helps us build more examples building on
this great work!

**Comment by lintool** [comment]
Closed by #56
