### ISSUE TITLE
How to use your project with pytorch？

### ISSUE THREAD

**Issue by briny-fish** [castorini/docTTTTTquery#58]
I only find your TensorFlow checkpoints. Don't you supply a pytorch checkpoint? Or didn‘t  your project supply a trained checkpoint?

**Comment by rodrigonogueira4** [comment]
https://github.com/castorini/docTTTTTquery#predicting-queries-from-passages-t5-inference-with-pytorch

**Comment by briny-fish** [comment]
Thank you for your reply.
