### ISSUE TITLE
doc preprocess

### ISSUE THREAD

**Issue by yixuan-qiao** [castorini/docTTTTTquery#59]
carefully read the script convert_msmarco_doc_to_t5_format.py, i found a constant 10000, 10000 characters not tokens which is small relative to the length of the document(median:584 max:333757). Maybe due to time efficiency?

    for doc_id, (doc_title, doc_text) in tqdm(corpus.items(), total=len(corpus)):
        doc = nlp(doc_text[:10000])
        sentences = [sent.string.strip() for sent in doc.sents]

**Comment by rodrigonogueira4** [comment]
That's correct. Otherwise, the model would spend too much time on these utterly long documents.
