### ISSUE TITLE
Segment documents

### ISSUE THREAD

**Issue by kite1988** [castorini/docTTTTTquery#60]
I was running "convert_msmarco_doc_to_t5_format.py" to segment each document using a sliding window of 10 sentences and stride of 5 sentences.  

```

for ITER in {00..32}; do
    python convert_msmarco_doc_to_t5_format.py  
        --corpus_path=msmarco-docs.tsv$ITER 
        --output_passage_texts_path=${OUTPUT_DIR}/passage_texts.txt$ITER 
        --output_passage_doc_ids_path=${OUTPUT_DIR}/msmarco_doc_passage_ids.txt$ITER
done

```

I am using Python 3.7.11 and spacy 2.1.6.  The log shows that some docs do not have any passages, eg, 

```
Wrote 638310 passages from 100000 docs.
There were 377 docs without passages.
```

Is this normal? What's the total number of passages for ms-marco document retrieval dataset after this segmentation?

Thanks!

**Comment by lintool** [comment]
See #59 - answer is yes.
