### ISSUE TITLE
Training in pytorch with GPUs?

### ISSUE THREAD

**Issue by littlewine** [castorini/docTTTTTquery#73]
Hi, is there a training script available for pytorch? 
The only [instructions](https://github.com/castorini/docTTTTTquery#Learning-a-New-Prediction-Model-T5-Training-with-TensorFlow) I see available assume that we will use TPUs on google cloud. 

Thanks!

**Comment by rodrigonogueira4** [comment]
Hello @littlewine, we have this (not tested) training script: https://github.com/castorini/pygaggle/blob/master/scripts/train_d2q.py

**Comment by littlewine** [comment]
Thanks a lot Rodrigo!
